use customer_behavior
select * from [dbo].[Customer]

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select
    customer_id,
    purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?

select top 5
    item_purchased,
    round(avg(review_rating), 2) as avg_rev_rating
from customer
group by item_purchased
order by avg_rev_rating desc;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select
    shipping_type,
    round(avg(purchase_amount), 2) as avg_purchase_amount
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select
    subscription_status,
    count(customer_id) as total_customers,
    round(avg(purchase_amount), 2) as avg_spend,
    round(sum(purchase_amount), 2) as total_revenue
from customer
group by subscription_status;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5
    item_purchased,
    round(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

select
    case
        when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as segmented_customers,
    previous_purchases
from customer

--Q8. What are the top 3 most purchased products within each category? 

with cte as (
    select
        category,
        item_purchased,
        count(customer_id) as total_orders,
        row_number()over(partition by category order by count(customer_id) desc) ranked_items
    from customer
    group by category, item_purchased
)
select ranked_items, category, item_purchased, total_orders
from cte
where ranked_items <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select
    subscription_status,
    count(customer_id) as repeat_customers
from customer
where previous_purchases > 5
group by subscription_status;

--Q10. What is the revenue contribution of each age group?

select
    age_group,
    sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;